### ISSUE TITLE
How to switch on/off the data with curl in bash?

### ISSUE THREAD

**Issue by hillz2** [DarrenWong/e3372-web-management#1]
Hi, I'm sorry if this isn't about python in the first place. I've been trying to connect and disconnect the internet on my E3372 based on your script but I'm doing in in curl. This is my curl script:
```
# First I obtain the cookie:
curl -sc '/tmp/E3372' 'http://192.168.8.1/html/home.html' > /dev/null
# Then I obtain the RequestVerificationToken:
token=$(curl -s http://192.168.8.1/api/webserver/SesTokInfo | awk -F "[><]" '/TokInfo/ {print $3}')
# Now I try to switch on the internet:
curl -X POST 'http://192.168.8.1/api/dialup/mobile-dataswitch' -H '__RequestVerificationToken: $token' -H 'Content-Type":"application/x-www-form-urlencoded; charset=UTF-8' --data '<?xml version="1.0" encoding="UTF-8"?><request><dataswitch>0</dataswitch></request>' --compressed
```
But then I get:
```
<?xml version="1.0" encoding="UTF-8"?>
<error>
<code>125002</code>
<message></message>
</error>
```
Sorry I'm not a programmer, can you help me how to fix that ? I just want to be able to switch on / off the internet via curl. Thanks

**Comment by DarrenWong** [comment]
You idea should be ok. But the response shows that you are sending the invalid post.
I think the curl post  should add the  Cookie info.
Here is a link for the curl post for your reference 
[http://stackoverflow.com/questions/38016641/sending-and-receiving-sms-by-command-line-with-huawei-e3131-and-hilink-on-a-debi](url)

**Comment by hillz2** [comment]
Thanks for the link, I've tried the solution on that link but still fails, here's my code:
```
#!/bin/bash

curl -sc '/tmp/E3372' 'http://192.168.8.1/html/home.html' > /dev/null
session=$(curl -sb /tmp/E3372 http://192.168.8.1/api/webserver/SesTokInfo | awk -F "[><]" '/SesInfo/ {print $3}')
token=$(curl -sb /tmp/E3372 http://192.168.8.1/api/webserver/SesTokInfo | awk -F "[><]" '/TokInfo/ {print $3}')
echo "Session: $session"
echo "Token: $token"
curl 'http://192.168.8.1/api/dialup/mobile-dataswitch' -H 'Host: 192.168.8.1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Referer: http://192.168.8.1/html/home.html' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H '__RequestVerificationToken: $token' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: $session' -H 'Connection: keep-alive' --data '<?xml version="1.0" encoding="UTF-8"?><request><dataswitch>0</dataswitch></request>' 
```

I've added `Cookie` too. Can you please help me debug what's wrong ?

**Comment by hillz2** [comment]
Oh my bad, I forgot to change `-H '__RequestVerificationToken: $token'` and `-H 'Cookie: $session'` to 
`-H "__RequestVerificationToken: $token"` and `-H "Cookie: $session"`

Thank you again for the help :dagger:

**Comment by DarrenWong** [comment]
Okay, seems you have solved your problem. 
I also use many times to solve the POST..
